import { InstrumentDescriptor } from '../types/audio';

export const soundLibrary: Record<string, InstrumentDescriptor> = {
  'kick-808': {
    key: 'kick-808',
    name: 'Kick 808',
    category: 'drums',
    defaultNote: 'C1',
    synthType: 'MembraneSynth',
    defaultSynthParams: { pitchDecay: 0.08, octaves: 8, decay: 0.5, release: 0.1 },
  },
  'kick-punchy': {
    key: 'kick-punchy',
    name: 'Kick Punchy',
    category: 'drums',
    defaultNote: 'C1',
    synthType: 'MembraneSynth',
    defaultSynthParams: { pitchDecay: 0.03, octaves: 5, decay: 0.25, release: 0.05 },
  },
  'kick-sub': {
    key: 'kick-sub',
    name: 'Sub Kick',
    category: 'drums',
    defaultNote: 'C1',
    synthType: 'MembraneSynth',
    defaultSynthParams: { pitchDecay: 0.12, octaves: 10, decay: 0.8, release: 0.2 },
  },
  'kick-snap': {
    key: 'kick-snap',
    name: 'Snap Kick',
    category: 'drums',
    defaultNote: 'C1',
    synthType: 'MembraneSynth',
    defaultSynthParams: { pitchDecay: 0.02, octaves: 3, decay: 0.15, release: 0.04 },
  },
  clap: {
    key: 'clap',
    name: 'Clap',
    category: 'drums',
    defaultNote: 'C4',
    synthType: 'NoiseSynth',
    defaultSynthParams: { noiseType: 'white', attack: 0.005, decay: 0.15 },
  },
  snare: {
    key: 'snare',
    name: 'Snare',
    category: 'drums',
    defaultNote: 'C4',
    synthType: 'NoiseSynth',
    defaultSynthParams: { noiseType: 'brown', attack: 0.01, decay: 0.3 },
  },
  'hihat-closed': {
    key: 'hihat-closed',
    name: 'Hi-Hat Closed',
    category: 'drums',
    defaultNote: 'C5',
    synthType: 'MetalSynth',
    defaultSynthParams: { harmonicity: 5.1, modulationIndex: 32, resonance: 4000, decay: 0.08 },
  },
  'hihat-open': {
    key: 'hihat-open',
    name: 'Hi-Hat Open',
    category: 'drums',
    defaultNote: 'C5',
    synthType: 'MetalSynth',
    defaultSynthParams: { harmonicity: 5.1, modulationIndex: 32, resonance: 4000, decay: 0.35 },
  },
  'bass-acid': {
    key: 'bass-acid',
    name: 'Acid Bass',
    category: 'bass',
    defaultNote: 'C2',
    synthType: 'MonoSynth',
    defaultSynthParams: {
      oscType: 'sawtooth',
      filterQ: 6,
      filterDecay: 0.15,
      attack: 0.005,
      decay: 0.2,
      sustain: 0.2,
    },
  },
  'bass-sub': {
    key: 'bass-sub',
    name: 'Sub Bass',
    category: 'bass',
    defaultNote: 'C2',
    synthType: 'MonoSynth',
    defaultSynthParams: {
      oscType: 'sine',
      filterQ: 1,
      filterDecay: 0.1,
      attack: 0.01,
      decay: 0.4,
      sustain: 0.3,
    },
  },
  'bass-reese': {
    key: 'bass-reese',
    name: 'Reese Bass',
    category: 'bass',
    defaultNote: 'C2',
    synthType: 'MonoSynth',
    defaultSynthParams: {
      oscType: 'sawtooth',
      filterQ: 4,
      filterDecay: 0.3,
      attack: 0.01,
      decay: 0.4,
      sustain: 0.4,
    },
  },
  'lead-fm': {
    key: 'lead-fm',
    name: 'FM Lead',
    category: 'synth',
    defaultNote: 'C4',
    synthType: 'FMSynth',
    defaultSynthParams: {
      harmonicity: 3,
      modulationIndex: 10,
      attack: 0.01,
      decay: 0.3,
      sustain: 0.3,
      release: 0.5,
    },
  },
  'lead-am': {
    key: 'lead-am',
    name: 'AM Lead',
    category: 'synth',
    defaultNote: 'C4',
    synthType: 'AMSynth',
    defaultSynthParams: {
      harmonicity: 3,
      attack: 0.01,
      decay: 0.3,
      sustain: 0.3,
      release: 0.5,
    },
  },
  'lead-pluck': {
    key: 'lead-pluck',
    name: 'Pluck',
    category: 'synth',
    defaultNote: 'C4',
    synthType: 'FMSynth',
    defaultSynthParams: {
      harmonicity: 2,
      modulationIndex: 20,
      attack: 0.001,
      decay: 0.1,
      sustain: 0,
      release: 0.1,
    },
  },

  // Tech House presets
  cowbell: {
    key: 'cowbell',
    name: 'Cowbell',
    category: 'drums',
    defaultNote: 'C5',
    synthType: 'MetalSynth',
    defaultSynthParams: { harmonicity: 5.6, modulationIndex: 16, resonance: 3500, decay: 0.3 },
  },
  rimshot: {
    key: 'rimshot',
    name: 'Rimshot',
    category: 'drums',
    defaultNote: 'C4',
    synthType: 'NoiseSynth',
    defaultSynthParams: { noiseType: 'white', attack: 0.001, decay: 0.04 },
  },
  shaker: {
    key: 'shaker',
    name: 'Shaker',
    category: 'drums',
    defaultNote: 'C5',
    synthType: 'NoiseSynth',
    defaultSynthParams: { noiseType: 'white', attack: 0.001, decay: 0.05 },
  },
  tom: {
    key: 'tom',
    name: 'Tom',
    category: 'drums',
    defaultNote: 'G2',
    synthType: 'MembraneSynth',
    defaultSynthParams: { pitchDecay: 0.06, octaves: 6, decay: 0.4, release: 0.1 },
  },
  'tech-stab': {
    key: 'tech-stab',
    name: 'Tech Stab',
    category: 'synth',
    defaultNote: 'C4',
    synthType: 'FMSynth',
    defaultSynthParams: { harmonicity: 6, modulationIndex: 20, attack: 0.001, decay: 0.08, sustain: 0, release: 0.05 },
  },
  'tech-pad': {
    key: 'tech-pad',
    name: 'Tech Pad',
    category: 'synth',
    defaultNote: 'C4',
    synthType: 'AMSynth',
    defaultSynthParams: { harmonicity: 2, attack: 0.4, decay: 0.3, sustain: 0.8, release: 2.0 },
  },
  'wobble-bass': {
    key: 'wobble-bass',
    name: 'Wobble Bass',
    category: 'bass',
    defaultNote: 'C2',
    synthType: 'MonoSynth',
    defaultSynthParams: {
      oscType: 'sawtooth',
      filterQ: 12,
      filterDecay: 0.2,
      attack: 0.005,
      decay: 0.3,
      sustain: 0.4,
    },
  },
};
